(define-library (kittens cat)
  (export lexer
          model-parser)
  (import (scheme base)
          (scheme file)
          (scheme char)
          (rebottled packrat))
  (include "cat/lexer.scm")
  (include "cat/expr.scm")
  (include "cat/stmt.scm")
  (include "cat/model.scm"))
