TSTS = $(wildcard *.tst)
SCM  = chibi-scheme -I $(ROOTDIR)/lib -I $(ROOTDIR)/vendor

.PHONY: test test-local
test: test-local

test-local: $(TSTS:.tst=.log)

%.log: %.tst
	@echo [TEST] running $<
	@$(SCM) $<
