#!/bin/sh
# ------------------------------------------------------------------------------
# Copyright (C) Huawei Technologies Co., Ltd. 2024. All rights reserved.
# SPDX-License-Identifier: MIT
# ------------------------------------------------------------------------------

case "$1" in
explode)
    shift
	exec ./explode "$@"
;;
*)
	exit 0
esac
