#!/bin/sh
set -e

INPUT="$1"
DIR=$(dirname "$0")
CROSS_COMPILE=aarch64-linux-gnu-
GCC="${CROSS_COMPILE}gcc"
OBJDUMP="${CROSS_COMPILE}objdump"

$DIR/defuse.scm "$INPUT" > /tmp/nope.c
$GCC -Iinclude -O3 -c -o /tmp/nope.o /tmp/nope.c
$OBJDUMP -S /tmp/nope.o > /tmp/nope.dump
$DIR/pasm.scm "$INPUT" /tmp/nope.dump
